FROM ubuntu:16.04
RUN groupadd -g 1000 c
RUN useradd -r -u 1000 -g c c
RUN apt-get update
RUN apt-get install -y net-tools
RUN apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat libsdl1.2-dev xterm python-crypto cpio python python3 \
     python3-pip python3-pexpect xz-utils debianutils iputils-ping libssl-dev
USER c:c
WORKDIR /home/c
ENTRYPOINT ["bash"]
