#!/bin/sh
if [ -x /usr/sbin/ifmetric -a "${IF_METRIC}" ]; then
    /usr/sbin/ifmetric "${IFACE}" "${IF_METRIC}"
fi

IF="usb0"
if [ "$IFACE" = "$IF" ]; then
  date >> /var/log/metric.log
  echo "$IF up" >> /var/log/metric.log
  /usr/sbin/ifmetric $IF 99
fi
